/** @type {import('tailwindcss').Config} */
// Design system "AdCraft Studio" — tokens alignés sur les maquettes (new design/).
// Tokens repris tels quels du design pour que le rendu corresponde à la maquette.
// Les classes vivent dans le HTML ET dans les gabarits JS (cartes en template
// literals) : scanner les deux, sinon le JIT n'émet pas leurs utilitaires.
module.exports = {
  content: ['./*.html', './js/**/*.js'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        outline: '#747686',
        'surface-dim': '#dadad9',
        'on-error': '#ffffff',
        error: '#ba1a1a',
        background: '#f9f9f8',
        'surface-container': '#eeeeed',
        'tertiary-fixed': '#ffdbcf',
        'tertiary-container': '#a73400',
        primary: '#0037b0',
        'secondary-fixed': '#e9e1dd',
        'secondary-fixed-dim': '#ccc5c2',
        'inverse-primary': '#b7c4ff',
        'secondary-container': '#e9e1dd',
        'on-error-container': '#93000a',
        'inverse-on-surface': '#f1f1f0',
        'inverse-surface': '#2f3130',
        'on-surface-variant': '#434655',
        'on-surface': '#1a1c1c',
        secondary: '#625d5b',
        surface: '#f9f9f8',
        'on-secondary-container': '#686361',
        'error-container': '#ffdad6',
        'surface-container-low': '#f3f4f3',
        'on-secondary': '#ffffff',
        'primary-container': '#1d4ed8',
        'on-secondary-fixed': '#1e1b19',
        tertiary: '#7f2500',
        'on-tertiary-fixed': '#390c00',
        'surface-tint': '#2151da',
        'on-primary-container': '#cad3ff',
        'surface-container-lowest': '#ffffff',
        'on-secondary-fixed-variant': '#4a4643',
        'on-background': '#1a1c1c',
        'on-tertiary-fixed-variant': '#832700',
        'primary-fixed': '#dce1ff',
        'on-primary-fixed-variant': '#0039b5',
        'outline-variant': '#c4c5d7',
        'on-tertiary-container': '#ffc9b7',
        'on-tertiary': '#ffffff',
        'tertiary-fixed-dim': '#ffb59c',
        'on-primary': '#ffffff',
        'surface-variant': '#e2e2e2',
        'surface-container-highest': '#e2e2e2',
        'on-primary-fixed': '#001551',
        'surface-bright': '#f9f9f8',
        'surface-container-high': '#e8e8e7',
        'primary-fixed-dim': '#b7c4ff',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        // full = cercle réel (avatars, pastilles). DESIGN.md front-matter: 9999px.
        full: '9999px',
      },
      spacing: {
        'container-max': '1280px',
        gutter: '20px',
        xl: '48px',
        lg: '24px',
        md: '16px',
        sm: '8px',
        unit: '4px',
        xs: '4px',
      },
      fontFamily: {
        // Titres : Space Grotesk (géométrique, du caractère). Corps/labels : Inter (lisible).
        sans: ['Inter', 'sans-serif'],
        display: ['"Space Grotesk"', 'sans-serif'],
        'display-xl': ['"Space Grotesk"', 'sans-serif'],
        'display-lg': ['"Space Grotesk"', 'sans-serif'],
        'display-lg-mobile': ['"Space Grotesk"', 'sans-serif'],
        'headline-md': ['"Space Grotesk"', 'sans-serif'],
        'body-base': ['Inter', 'sans-serif'],
        'body-sm': ['Inter', 'sans-serif'],
        'label-md': ['Inter', 'sans-serif'],
        'label-sm': ['Inter', 'sans-serif'],
      },
      fontSize: {
        // Titre hero accueil (exception maquette : 52/58). Voir PROMPT-INTEGRATION.
        'display-xl': ['52px', { lineHeight: '58px', letterSpacing: '-0.03em', fontWeight: '600' }],
        'display-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '600' }],
        'display-lg-mobile': ['24px', { lineHeight: '32px', letterSpacing: '-0.02em', fontWeight: '600' }],
        'headline-md': ['20px', { lineHeight: '28px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'body-base': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'body-sm': ['13px', { lineHeight: '18px', fontWeight: '400' }],
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.01em', fontWeight: '600' }],
        'label-sm': ['11px', { lineHeight: '14px', fontWeight: '400' }],
      },
    },
  },
  plugins: [require('@tailwindcss/forms')],
};
